server:
  port: 10000
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6660/eureka
zuul:
  routes:
    api-hi:
      path: /api-feign/**
      serviceId: consumer-openfeigh
    api-bye:
      path: /api-rest/**
      serviceId: consumer-rest
